import React, { useEffect, useState } from 'react';
import { ArrowUpRight, BrainCircuit, Bot, ChevronDown, Code2, ExternalLink, Github, Mail, MapPin, Menu, Send, ShieldCheck, Sparkles, X } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import PortfolioScene from './PortfolioScene';
import './styles.css';
import './reference-theme.css';

const PROFILE_IMAGE = 'https://raw.githubusercontent.com/Nithishrish23/Nithish-portfolio/98f873233766d9efe6688b559262306092e7545d/static/images/1727781988320.jpg';
const EMAIL = 'nithishkumar140700@gmail.com';
const RESUME_URL = 'https://raw.githubusercontent.com/Nithishrish23/Nithish-portfolio/main/static/files/nithishresume(1).pdf';

const BRAND_ICONS = {
  OpenAI:'https://cdn.simpleicons.org/openai', Claude:'https://cdn.simpleicons.org/anthropic', Gemini:'https://cdn.simpleicons.org/googlegemini', Ollama:'https://cdn.simpleicons.org/ollama', LangChain:'https://cdn.simpleicons.org/langchain', Llama:'https://cdn.simpleicons.org/meta', RAG:'https://cdn.simpleicons.org/weaviate', MCP:'https://cdn.simpleicons.org/modelcontextprotocol',
  Python:'https://cdn.simpleicons.org/python', FastAPI:'https://cdn.simpleicons.org/fastapi', Django:'https://cdn.simpleicons.org/django', Flask:'https://cdn.simpleicons.org/flask', PostgreSQL:'https://cdn.simpleicons.org/postgresql', MySQL:'https://cdn.simpleicons.org/mysql', Redis:'https://cdn.simpleicons.org/redis', Celery:'https://cdn.simpleicons.org/celery',
  React:'https://cdn.simpleicons.org/react', 'Next.js':'https://cdn.simpleicons.org/nextdotjs', TypeScript:'https://cdn.simpleicons.org/typescript', Tailwind:'https://cdn.simpleicons.org/tailwindcss', 'Three.js':'https://cdn.simpleicons.org/threedotjs', Vite:'https://cdn.simpleicons.org/vite', WebGL:'https://cdn.simpleicons.org/webgl', GSAP:'https://cdn.simpleicons.org/greensock',
  Docker:'https://cdn.simpleicons.org/docker', Git:'https://cdn.simpleicons.org/git', Linux:'https://cdn.simpleicons.org/linux', AWS:'https://cdn.simpleicons.org/amazonaws', Vercel:'https://cdn.simpleicons.org/vercel', Azure:'https://cdn.simpleicons.org/microsoftazure', GitHub:'https://cdn.simpleicons.org/github', 'CI/CD':'https://cdn.simpleicons.org/githubactions',
};
const technologyGroups=[
 {number:'01',title:'AI & LLM',lead:'Intelligence layer',icon:BrainCircuit,items:['OpenAI','Claude','Gemini','Ollama','LangChain','Llama','RAG','MCP']},
 {number:'02',title:'Backend & Data',lead:'Systems layer',icon:Code2,items:['Python','FastAPI','Django','Flask','PostgreSQL','MySQL','Redis','Celery']},
 {number:'03',title:'Frontend & 3D',lead:'Experience layer',icon:Code2,items:['React','Next.js','TypeScript','Tailwind','Three.js','Vite','WebGL','GSAP']},
 {number:'04',title:'Tools & Cloud',lead:'Delivery layer',icon:Code2,items:['Docker','Git','Linux','AWS','Vercel','Azure','GitHub','CI/CD']},
];
const work=[
 {index:'01',title:'Salesforce AI Copilot',category:'AI / Enterprise Automation',description:'Permission-aware AI with RAG, MCP orchestration, conversational workflows, validation, approvals and auditability before critical actions.',stack:['FastAPI','React','RAG','MCP','Salesforce','OpenAI','Claude'],repo:'https://github.com/Nithishrish23/Salesforce-ai'},
 {index:'02',title:'Multi-Agent Finance Platform',category:'AI Agents / Finance',description:'Provider-agnostic LLM routing, DAG workflows, memory, finance analysis, notifications and a fail-closed risk layer.',stack:['Next.js','FastAPI','PostgreSQL','Redis','Celery'],repo:'https://github.com/Nithishrish23/agent-earning'},
 {index:'03',title:'Full-Stack Commerce Platform',category:'Product Engineering',description:'B2B/B2C commerce across customer, seller and admin workflows with Python APIs, PostgreSQL, authentication and payments.',stack:['React','Vite','Flask','PostgreSQL','JWT','Stripe'],repo:'https://github.com/Nithishrish23'},
 {index:'04',title:'KYC Document Intelligence',category:'Computer Vision',description:'Computer-vision workflows for PAN, Aadhaar, address and signature documents with page classification and Aadhaar masking.',stack:['Python','YOLO','OpenCV','PIL'],repo:'https://github.com/Nithishrish23'},
];
const companies=[['MathuraTech','Technology & digital work','https://mathuratech.com'],['Popular Traders','Web product work','https://populartraders.mathuratech.com'],['Infu Digital','Digital growth & web','https://infudigital.com'],['Ninai Technologies','AI & technology solutions','https://www.ninaitechnologies.com']];
const capabilities=[{icon:BrainCircuit,title:'LLM Engineering',text:'OpenAI, Claude, Gemini, LLaMA, OpenRouter, structured outputs and tool calling.'},{icon:Bot,title:'AI Agents & RAG',text:'Agent orchestration, retrieval, memory, MCP, workflows and permission-aware automation.'},{icon:Code2,title:'Backend & Product',text:'Python, FastAPI, Flask, Django, React, Next.js, PostgreSQL and scalable APIs.'},{icon:ShieldCheck,title:'Reliable AI',text:'Validation, approvals, role controls, auditability, testing and fail-closed execution.'}];
const experience=[{period:'JUN 2025 — PRESENT',role:'Software Engineer - II',company:'CodeDTX Solutions PVT LTD',text:'Salesforce API and Metadata integrations, intelligent automation, permission-aware action engines and LLM-powered conversational interfaces.'},{period:'OCT 2024 — JUN 2025',role:'Team Lead',company:'PCL INFOTECH PVT LTD',text:'B2B/B2C e-commerce engineering with Flask, React and PostgreSQL, plus AI agents for business automation.'},{period:'AUG 2023 — OCT 2024',role:'AI Software Associate',company:'Green Books',text:'AI/ML and image-identification software with backend optimization, testing, deployment and security.'},{period:'DEC 2022 — MAR 2023',role:'Data Analyst Intern',company:'Skill-Lync',text:'Trend and correlation analysis with Tableau and Excel visualizations.'}];

function App(){
 const [menuOpen,setMenuOpen]=useState(false),[intro,setIntro]=useState(true),[theme,setTheme]=useState('light');
 const [form,setForm]=useState({fullname:'',email:'',country:'',mobile:'',message:''}),[status,setStatus]=useState({type:'',message:''}),[sending,setSending]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem('portfolio-theme')||'light';setTheme(saved);document.documentElement.dataset.theme=saved;const t=setTimeout(()=>setIntro(false),900);return()=>clearTimeout(t)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('portfolio-theme',theme)},[theme]);
 const go=id=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});setMenuOpen(false)};
 const setField=(k,v)=>setForm(c=>({...c,[k]:v}));
 const submit=async e=>{e.preventDefault();setSending(true);setStatus({type:'',message:''});try{const res=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await res.json().catch(()=>({}));if(res.ok&&!data.fallback){setStatus({type:'success',message:'Message sent successfully. I will get back to you soon.'});setForm({fullname:'',email:'',country:'',mobile:'',message:''})}else if(data.fallback){const subject=encodeURIComponent(`Portfolio enquiry from ${form.fullname}`);const body=encodeURIComponent(`Name: ${form.fullname}\nEmail: ${form.email}\nCountry: ${form.country}\nMobile: ${form.mobile}\n\n${form.message}`);window.location.href=`mailto:${EMAIL}?subject=${subject}&body=${body}`;setStatus({type:'success',message:'Your email app is opening with the message ready to send.'})}else throw new Error(data.message||'Unable to send your message.')}catch(err){setStatus({type:'error',message:err.message})}finally{setSending(false)}};
 return <div className="site">
  <div className={`intro-screen ${intro?'show':''}`} aria-hidden={!intro}><div className="intro-ring"><img src={PROFILE_IMAGE} alt=""/></div><div className="intro-name">NITHISH KUMAR</div><div className="intro-status"><span/> INITIALIZING</div></div>
  <header className="nav-wrap"><nav className="nav container"><button className="brand" onClick={()=>go('home')} aria-label="Back to home"><span className="brand-mark"><img className="brand-photo" src={PROFILE_IMAGE} alt="Nithish Kumar"/></span><span><strong>Nithish Kumar</strong><small>AI Engineer &amp; Full Stack Developer</small></span></button><div className={`nav-links ${menuOpen?'open':''}`}>{[['home','Home'],['about','About'],['work','Projects'],['experience','Experience'],['stack','Tech Stack'],['contact','Contact']].map(([id,label])=><button key={id} className={id==='home'?'active':''} onClick={()=>go(id)}>{label}</button>)}<a href="https://github.com/Nithishrish23" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={13}/></a></div><div className="nav-actions"><button className="theme-toggle" onClick={()=>setTheme(t=>t==='light'?'dark':'light')} aria-label="Toggle theme"><span>{theme==='light'?'☼':'☾'}</span></button><button className="nav-cta" onClick={()=>go('contact')}>Let's Talk <ArrowUpRight size={14}/></button><button className="menu-btn" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen?<X/>:<Menu/>}</button></div></nav></header>
  <main>
   <section id="home" className="hero container"><div className="hero-copy reveal"><div className="eyebrow">BUILD · AUTOMATE · INNOVATE</div><div className="availability"><b/> Open to opportunities</div><h1>Turning ideas into<br/>real-world <em>solutions.</em></h1><p className="hero-text">I'm Nithish Kumar, an AI Engineer &amp; Full Stack Developer focused on LLM applications, RAG, AI agents, automation and scalable web systems that create real impact.</p><div className="hero-meta"><span><MapPin size={16}/> Chennai, India</span><span><Sparkles size={16}/> Open to opportunities</span><span><Bot size={16}/> Let's build together</span></div><div className="hero-actions"><button className="primary-btn" onClick={()=>go('work')}>View My Work <ArrowUpRight size={16}/></button><button className="ghost-btn" onClick={()=>window.open(RESUME_URL,'_blank')}>Download Resume ↓</button></div><div className="hero-metrics"><div><strong>4+</strong><span>Years Experience</span></div><div><strong>20+</strong><span>Projects Built</span></div><div><strong>5+</strong><span>Domains</span></div><div><strong>∞</strong><span>Continuous Learning</span></div></div></div><div className="hero-visual"><PortfolioScene/><div className="hero-scene-copy"><div className="scene-pill"><BrainCircuit size={18}/><span><b>AI</b> Think</span></div><div className="scene-pill"><Code2 size={18}/><span><b>Code</b> Build</span></div><div className="scene-pill"><Bot size={18}/><span><b>Automate</b> Scale</span></div><div className="scene-pill"><Sparkles size={18}/><span><b>Impact</b> Repeat</span></div></div><div className="hero-photo-card"><img src={PROFILE_IMAGE} alt="Nithish Kumar portrait"/><div><span>AI ENGINEER</span><strong>NITHISH KUMAR</strong></div></div></div></section>
   <section id="about" className="section container about-section"><div className="section-head"><span className="section-number">01</span><div><p className="section-kicker">ABOUT</p><h2>Engineering <span>real impact.</span></h2></div><p className="section-note">AI, backend, interfaces and automation designed as one production system.</p></div><div className="about-grid"><div className="about-statement"><p>I work at the intersection of <strong>AI and product engineering</strong>, with a Python-first approach and a strong focus on reliable execution.</p><p>My work spans conversational AI, Salesforce automation, multi-agent workflows, retrieval systems, computer vision and production web applications.</p><div className="signature-line"><span>CHENNAI · INDIA</span><span>AI · FULL STACK · AUTOMATION</span></div></div><div className="capability-list">{capabilities.map(({icon:Icon,title,text})=><article key={title}><Icon size={20}/><div><h3>{title}</h3><p>{text}</p></div><ArrowUpRight size={15}/></article>)}</div></div></section>
   <section id="work" className="section work-section"><div className="container"><div className="section-head"><span className="section-number">02</span><div><p className="section-kicker">PROJECTS</p><h2>Systems I've <span>shipped.</span></h2></div><p className="section-note">AI, automation, backend and product engineering with real implementation depth.</p></div><div className="work-list">{work.map(item=><article className="work-row" key={item.title}><div className="work-index">{item.index}</div><div className="work-main"><p className="work-category">{item.category}</p><h3>{item.title}</h3><p>{item.description}</p><div className="stack">{item.stack.map(s=><span key={s}>{s}</span>)}</div></div><a className="work-link" href={item.repo} target="_blank" rel="noreferrer"><Github size={18}/><ArrowUpRight size={14}/></a></article>)}</div></div></section>
   <section className="section company-section"><div className="container"><div className="section-head compact"><span className="section-number">03</span><div><p className="section-kicker">REAL-WORLD WORK</p><h2>Built for <span>business.</span></h2></div></div><p className="company-intro">Technology and digital product work across AI-first businesses and web platforms.</p><div className="company-grid">{companies.map(([name,detail,href])=><a href={href} target="_blank" rel="noreferrer" className="company-card" key={name}><div className="company-symbol">{name[0]}</div><div><h3>{name}</h3><p>{detail}</p></div><ExternalLink size={15}/></a>)}</div></div></section>
   <section id="experience" className="section experience-section"><div className="container"><div className="section-head"><span className="section-number">04</span><div><p className="section-kicker">EXPERIENCE</p><h2>Experience with <span>depth.</span></h2></div></div><div className="experience-layout"><div className="experience-intro"><p>Engineering across AI, software, analytics and full-stack product development.</p><div className="experience-rule"/><span>2022 — NOW</span></div><div className="timeline">{experience.map(item=><article key={item.company}><span className="period">{item.period}</span><div><h3>{item.role}</h3><h4>{item.company}</h4><p>{item.text}</p></div></article>)}</div></div></div></section>
   <section id="stack" className="section stack-section"><div className="container"><div className="stack-banner"><div><p className="section-kicker">TECHNOLOGY</p><h2>Engineered in <span>layers.</span></h2></div><p>A focused toolkit across AI, backend, frontend, 3D and cloud to build, deploy and scale real-world solutions.</p></div><div className="technology-grid">{technologyGroups.map(group=>{const GroupIcon=group.icon;return <article className="technology-card" key={group.title}><div className="technology-card-head"><div className="technology-icon"><GroupIcon size={22}/></div><div><div className="technology-top"><span>{group.number}</span><small>{group.lead}</small></div><h3>{group.title}</h3></div></div><div className="technology-items">{group.items.map(item=><span key={item}><img src={BRAND_ICONS[item]} alt={`${item} logo`} loading="lazy"/><b>{item}</b></span>)}</div></article>)})}</div></div></section>
   <section id="contact" className="section contact-section"><div className="container contact-grid"><div className="contact-copy"><span className="section-number">05</span><p className="section-kicker">LET'S BUILD</p><h2>Have a hard problem?<br/><span>Let's make it software.</span></h2><p>For AI products, intelligent automation, full-stack systems or engineering opportunities, send a message.</p><div className="direct-contact"><a href={`mailto:${EMAIL}`}><Mail size={16}/> {EMAIL}</a><span><MapPin size={16}/> Chennai, Tamil Nadu, India</span></div></div><form className="contact-form" onSubmit={submit}><div className="form-title"><span>CONTACT</span><b>Tell me what you're building.</b></div><div className="form-row"><input required value={form.fullname} onChange={e=>setField('fullname',e.target.value)} placeholder="Full name"/><input required type="email" value={form.email} onChange={e=>setField('email',e.target.value)} placeholder="Email address"/></div><div className="form-row"><input required value={form.country} onChange={e=>setField('country',e.target.value)} placeholder="Country"/><input required value={form.mobile} onChange={e=>setField('mobile',e.target.value)} placeholder="Mobile number"/></div><textarea required value={form.message} onChange={e=>setField('message',e.target.value)} placeholder="Tell me about the project or opportunity" rows="6"/><button className="primary-btn send-btn" disabled={sending}>{sending?'Preparing…':<>Send message <Send size={16}/></>}</button>{status.message&&<div className={`form-status ${status.type}`}>{status.message}</div>}</form></div></section>
  </main>
  <footer className="footer container"><div className="footer-brand"><img className="brand-photo" src={PROFILE_IMAGE} alt="Nithish Kumar"/><div><strong>Nithish Kumar</strong><span>AI Engineer · Full Stack Developer</span></div></div><div className="footer-links"><a href="https://github.com/Nithishrish23" target="_blank" rel="noreferrer"><Github size={15}/> GitHub</a><span>BUILD · AUTOMATE · INNOVATE</span></div></footer>
 </div>;
}

createRoot(document.getElementById('root')).render(<App/>);
