import { useEffect, useState } from 'react';
import { ArrowDown, ArrowUpRight, BrainCircuit, Check, Code2, Database, Mail, MapPin, Menu, Phone, Send, Sparkles, X, Cloud, Smartphone, Layers3 } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import PortfolioScene from './PortfolioScene';
import './styles.css';

const PROFILE_IMAGE = 'https://raw.githubusercontent.com/Nithishrish23/Nithish-portfolio/98f873233766d9efe6688b559262306092e7545d/static/images/1727781988320.jpg';
const EMAIL = 'nithishkumar.job@gmail.com';
const PHONE = '+91 7708358913';

const BRAND_ICONS = { Python:'https://cdn.simpleicons.org/python', FastAPI:'https://cdn.simpleicons.org/fastapi', React:'https://cdn.simpleicons.org/react', 'Next.js':'https://cdn.simpleicons.org/nextdotjs', Flutter:'https://cdn.simpleicons.org/flutter', 'Node.js':'https://cdn.simpleicons.org/nodedotjs', PostgreSQL:'https://cdn.simpleicons.org/postgresql', MongoDB:'https://cdn.simpleicons.org/mongodb', AWS:'https://cdn.simpleicons.org/amazonaws/FF9900', Azure:'https://cdn.simpleicons.org/microsoftazure/0078D4', Docker:'https://cdn.simpleicons.org/docker', Git:'https://cdn.simpleicons.org/git', OpenAI:'https://cdn.simpleicons.org/openai', Claude:'https://cdn.simpleicons.org/anthropic', Gemini:'https://cdn.simpleicons.org/googlegemini', Ollama:'https://cdn.simpleicons.org/ollama', LangChain:'https://cdn.simpleicons.org/langchain', RAG:'https://cdn.simpleicons.org/weaviate', MCP:'https://cdn.simpleicons.org/modelcontextprotocol' };
const skillGroups = [
  { title:'AI & Automation', subtitle:'LLM · RAG · AI Agents', icon:BrainCircuit, items:['OpenAI','Claude','Gemini','Ollama','LangChain','RAG','MCP'] },
  { title:'Web Development', subtitle:'React · Next.js · Python', icon:Code2, items:['React','Next.js','FastAPI','Python','Node.js'] },
  { title:'Mobile Development', subtitle:'Flutter · Android · iOS', icon:Smartphone, items:['Flutter','React'] },
  { title:'Cloud & DevOps', subtitle:'AWS · Azure · Docker', icon:Cloud, items:['AWS','Azure','Docker','Git'] },
  { title:'Database & Systems', subtitle:'PostgreSQL · MongoDB', icon:Database, items:['PostgreSQL','MongoDB','Python','FastAPI'] },
  { title:'Product Engineering', subtitle:'Build · Ship · Scale', icon:Layers3, items:['React','Next.js','FastAPI','Python','Git'] }
];
const projects = [
  { title:'AI Agent Platform', type:'AI · AUTOMATION', text:'AI agents that connect models, tools and business workflows with controlled execution.', stack:['React','FastAPI','PostgreSQL'], accent:'01' },
  { title:'Salesforce AI Copilot', type:'ENTERPRISE AI', text:'Permission-aware conversational automation with RAG, MCP, validation, approvals and auditability.', stack:['FastAPI','RAG','MCP'], accent:'02' },
  { title:'SaaS Local Shop', type:'MOBILE · SAAS', text:'Flutter product for local businesses with customer, admin and operational workflows.', stack:['Flutter','Node.js','PostgreSQL'], accent:'03' },
  { title:'KYC Document Intelligence', type:'COMPUTER VISION', text:'Document classification and extraction for PAN, Aadhaar, address and signature workflows.', stack:['Python','YOLO','OpenCV'], accent:'04' }
];
const experience = [
  ['2025 — NOW','Software Engineer - II','CodeDTX Solutions PVT LTD','Salesforce API and Metadata integrations, intelligent automation, permission-aware action engines and LLM-powered conversational interfaces.'],
  ['2024 — 2025','Team Lead','PCL INFOTECH PVT LTD','B2B/B2C commerce engineering with Flask, React and PostgreSQL, plus AI agents for business automation.'],
  ['2023 — 2024','AI Software Associate','Green Books','AI/ML and image-identification software with backend optimization, testing, deployment and security.'],
  ['2022 — 2023','Data Analyst Intern','Skill-Lync','Trend and correlation analysis with Tableau and Excel visualizations.']
];
const navItems = [['home','Home'],['about','About'],['skills','Skills'],['projects','Projects'],['experience','Experience'],['contact','Contact']];
const emptyForm = { fullname:'', email:'', mobile:'', message:'' };

function App(){
  const [menuOpen,setMenuOpen]=useState(false), [intro,setIntro]=useState(true), [activeProject,setActiveProject]=useState(null), [legal,setLegal]=useState(null), [form,setForm]=useState(emptyForm), [status,setStatus]=useState({type:'',message:''}), [sending,setSending]=useState(false);
  useEffect(()=>{document.documentElement.dataset.theme='dark'; const timer=setTimeout(()=>setIntro(false),850); return()=>clearTimeout(timer)},[]);
  const go=(id)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});setMenuOpen(false)};
  const submit=async(e)=>{e.preventDefault();setSending(true);setStatus({type:'',message:''});try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json().catch(()=>({}));if(r.ok&&!d.fallback){setStatus({type:'success',message:'Message sent successfully.'});setForm(emptyForm)}else{const subject=encodeURIComponent(`Portfolio enquiry from ${form.fullname}`),body=encodeURIComponent(`Name: ${form.fullname}\nEmail: ${form.email}\nMobile: ${form.mobile}\n\n${form.message}`);window.location.href=`mailto:${EMAIL}?subject=${subject}&body=${body}`;setStatus({type:'success',message:'Your email app is opening with the message ready.'})}}catch(err){setStatus({type:'error',message:err.message||'Unable to send message.'})}finally{setSending(false)}};
  return <div className="site night-portfolio">
    <div className={`intro-screen ${intro?'show':''}`} aria-hidden={!intro}><div className="intro-ring"><img src={PROFILE_IMAGE} alt=""/></div><div className="intro-name">NITHISH KUMAR</div><div className="intro-status"><span/> INITIALIZING PORTFOLIO</div></div>
    <div className="background-field" aria-hidden="true"><span className="orb orb-a"/><span className="orb orb-b"/><span className="orb orb-c"/><span className="scanline"/></div>
    <header className="nav-wrap"><nav className="nav container"><button className="brand" onClick={()=>go('home')} aria-label="Back to home"><span className="brand-mark"><img className="brand-photo" src={PROFILE_IMAGE} alt="Nithish Kumar"/></span><span><strong>NITHISH KUMAR</strong><small>AI ENGINEER · FULL STACK</small></span></button><div className={`nav-links ${menuOpen?'open':''}`}>{navItems.map(([id,label])=><button key={id} className={id==='home'?'active':''} onClick={()=>go(id)}>{label}</button>)}</div><div className="nav-actions"><button className="nav-cta" onClick={()=>go('contact')}>Let's Connect <ArrowUpRight size={14}/></button><button className="menu-btn" onClick={()=>setMenuOpen(v=>!v)} aria-label="Toggle navigation">{menuOpen?<X/>:<Menu/>}</button></div></nav></header>
    <main>
      <section id="home" className="hero container"><div className="hero-copy reveal"><div className="eyebrow"><span/> AI ENGINEER · FULL STACK DEVELOPER</div><div className="availability"><b/> AVAILABLE FOR SELECTED WORK</div><h1>Turning ideas<br/>into real-world<br/><em>solutions.</em></h1><p className="hero-text">I build intelligent products, AI agents, scalable APIs and modern web & mobile experiences that turn complex ideas into useful software.</p><div className="hero-actions"><button className="primary-btn" onClick={()=>go('projects')}>View My Work <ArrowUpRight size={16}/></button><button className="ghost-btn" onClick={()=>go('contact')}>Contact Me <Send size={15}/></button></div><div className="hero-metrics"><div><strong>4+</strong><span>YEARS</span></div><div><strong>20+</strong><span>PROJECTS</span></div><div><strong>AI</strong><span>FOCUS</span></div><div><strong>∞</strong><span>LEARNING</span></div></div><div className="hero-contact"><a href={`mailto:${EMAIL}`}><Mail size={15}/>{EMAIL}</a><a href={`tel:${PHONE.replace(/\s/g,'')}`}><Phone size={15}/>{PHONE}</a><span><MapPin size={15}/>Chennai, India</span></div></div><div className="hero-visual"><PortfolioScene/><div className="scene-card scene-left"><Code2 size={18}/><b>Code · Deploy<br/>Scale · Repeat</b></div><div className="scene-card scene-right"><Sparkles size={18}/><b>Ideas · Automation<br/>AI · Impact</b></div><div className="avatar-caption"><strong>360°</strong><span>DRAG TO ROTATE</span><ArrowDown size={15}/></div></div></section>
      <section id="about" className="section container"><div className="section-head"><span className="section-number">01</span><div><p className="section-kicker">ABOUT</p><h2>Engineering <span>with purpose.</span></h2></div><p className="section-note">AI, product engineering and automation connected into practical production systems.</p></div><div className="about-grid"><div className="about-statement"><p>I work at the intersection of <strong>AI and product engineering</strong>, building Python-first systems with reliable execution, clean interfaces and scalable APIs.</p><p>My work spans conversational AI, Salesforce automation, multi-agent workflows, RAG, computer vision and production web applications.</p><div className="about-facts"><span><Check size={14}/> Python-first</span><span><Check size={14}/> Production minded</span><span><Check size={14}/> AI native</span></div></div><div className="about-panel"><div className="panel-label">CORE CAPABILITIES</div>{[['AI Engineering','LLM · RAG · Agents'],['Automation','MCP · Workflows · APIs'],['Product','Web · Mobile · 3D'],['Reliability','Validation · Security · Audit']].map(([a,b])=><button key={a} onClick={()=>go('skills')}><span><b>{a}</b><small>{b}</small></span><ArrowUpRight size={15}/></button>)}</div></div></section>
      <section id="skills" className="section skills-section"><div className="container"><div className="section-head"><span className="section-number">02</span><div><p className="section-kicker">TECH STACK</p><h2>Tools that <span>ship.</span></h2></div><p className="section-note">Tap a layer to explore the technology behind the work.</p></div><div className="skill-grid">{skillGroups.map(g=>{const Icon=g.icon;return <article className="skill-card" key={g.title} onClick={()=>go('projects')}><div className="skill-icon"><Icon size={21}/></div><div className="skill-copy"><p>{g.subtitle}</p><h3>{g.title}</h3></div><ArrowUpRight size={15}/><div className="skill-items">{g.items.map(i=><span key={i}><img src={BRAND_ICONS[i]||'/icon-fallback.svg'} alt=""/>{i}</span>)}</div></article>})}</div></div></section>
      <section id="projects" className="section projects-section"><div className="container"><div className="section-head"><span className="section-number">03</span><div><p className="section-kicker">FEATURED PROJECTS</p><h2>Built to <span>matter.</span></h2></div><p className="section-note">Click a project to reveal its implementation focus.</p></div><div className="project-grid">{projects.map(p=><article className={`project-card ${activeProject===p.title?'selected':''}`} key={p.title} onClick={()=>setActiveProject(activeProject===p.title?null:p.title)}><div className="project-top"><span>{p.accent}</span><small>{p.type}</small></div><h3>{p.title}</h3><p>{p.text}</p><div className="project-stack">{p.stack.map(s=><span key={s}>{s}</span>)}</div><div className="project-open"><span>{activeProject===p.title?'CLOSE DETAILS':'VIEW DETAILS'}</span><ArrowUpRight size={16}/></div>{activeProject===p.title&&<div className="project-detail"><b>ROLE</b><span>Architecture · Development · AI integration · Deployment</span><b>FOCUS</b><span>Reliable systems, responsive UI and production-ready workflows.</span></div>}</article>)}</div></div></section>
      <section id="experience" className="section experience-section"><div className="container"><div className="section-head"><span className="section-number">04</span><div><p className="section-kicker">EXPERIENCE</p><h2>A path of <span>building.</span></h2></div><p className="section-note">From analytics and AI/ML to full-stack engineering and enterprise automation.</p></div><div className="timeline">{experience.map(([period,role,company,text])=><article key={company}><span className="period">{period}</span><div className="timeline-dot"/><div><h3>{role}</h3><h4>{company}</h4><p>{text}</p></div></article>)}</div></div></section>
      <section id="contact" className="section contact-section"><div className="container contact-grid"><div className="contact-copy"><span className="section-number">05</span><p className="section-kicker">LET'S CONNECT</p><h2>Have an idea?<br/><span>Let's build it.</span></h2><p>AI products, intelligent automation, full-stack systems and engineering opportunities.</p><div className="contact-links"><a href={`mailto:${EMAIL}`}><Mail size={17}/><span>{EMAIL}</span></a><a href={`tel:${PHONE.replace(/\s/g,'')}`}><Phone size={17}/><span>{PHONE}</span></a><span><MapPin size={17}/><span>Chennai, Tamil Nadu, India</span></span></div></div><form className="contact-form" onSubmit={submit}><div className="form-title"><span>START A CONVERSATION</span><b>Tell me what you're building.</b></div><div className="form-row"><input required value={form.fullname} onChange={e=>setForm({...form,fullname:e.target.value})} placeholder="Your name"/><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Email address"/></div><input value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})} placeholder="Phone number"/><textarea required rows="5" value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Project, role or idea"/><button className="primary-btn send-btn" disabled={sending}>{sending?'SENDING…':<>Send message <Send size={16}/></>}</button>{status.message&&<div className={`form-status ${status.type}`}>{status.message}</div>}</form></div></section>
    </main>
    <footer className="footer container"><div className="footer-main"><div className="footer-brand"><img src={PROFILE_IMAGE} alt="Nithish Kumar"/><div><strong>NITHISH KUMAR</strong><span>AI Engineer · Full Stack Developer</span></div></div><div className="footer-actions"><button onClick={()=>setLegal('privacy')}>Privacy</button><button onClick={()=>setLegal('terms')}>Terms</button><button onClick={()=>go('home')}>Back to top <ArrowUpRight size={13}/></button></div></div><div className="footer-bottom"><span>© 2026 Nithish Kumar. All rights reserved.</span><span>AI · AUTOMATION · SOFTWARE</span></div></footer>
    {legal&&<div className="legal-backdrop" onClick={()=>setLegal(null)}><div className="legal-modal" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><button className="legal-close" onClick={()=>setLegal(null)}><X size={17}/></button><p className="section-kicker">{legal==='privacy'?'PRIVACY':'TERMS'}</p><h2>{legal==='privacy'?'Privacy Policy':'Terms of Use'}</h2>{legal==='privacy'?<><p>This portfolio collects only information you choose to submit through the contact form, such as your name, email, phone number and message, for responding to your enquiry.</p><p>No personal information is intentionally sold or shared for advertising. Do not submit passwords, payment information or other sensitive credentials.</p></>:<><p>This website is a personal portfolio. Project names, descriptions and technologies are presented for professional context and may change as work evolves.</p><p>Content is provided for general informational purposes. Contact information submitted through the form is intended for communication about your enquiry.</p></>}<div className="legal-rule"/><button className="ghost-btn" onClick={()=>setLegal(null)}>Close</button></div></div>}
  </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
